version: '3'
services:
  portainer:
    image: "portainer/portainer"
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/portainer:/data

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./.docker/nginx/server/server.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html
    ports:
      - "80:80"
    restart: always


  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/:/docker-entrypoint-initdb.d/
      - ./.docker/postgres/data:/var/lib/postgresql/data

  phpfpm:
    build: ./.docker/php-fpm-8
    container_name: php8-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./.docker/php-fpm-8/conf/etc/:/usr/local/etc
      #- ./.docker/php-fpm-8/php.ini:/usr/local/etc/php/php.ini
      #- ./.docker/log/php-fpm:/var/log/php-fpm
      - ./www/:/var/www/html/

  redis:
    image: redis:5-alpine
    container_name: redis
    ports: [ "6379" ]

  # rabbitmq:
  #     image: rabbitmq:3.7-management
  #     ports: [5672,15672]
